version: '3'
services:
  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    ports:
      - 27017:27017

  backend:
    build:
      context: ./trello-backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/trello-db

  frontend:
    build:
      context: ./trello
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:8000/api

volumes:
  mongodb_data: